POST http://localhost:4000/board
Content-Type: application/json
Authorization: Bearer sdlfkglskdfglskdflkgslkdflgklkdfg_token

{
  "fullName": "zkjcuasuias",
  "nickname": "genius ",
  "age": 11
}

###

POST http://localhost:4000/board
Content-Type: application/json

{
  "fullName": "고경준 천재님이십니단dlkfsldkflskdf",
  "nickname": "genius ",
  "age": 11,
  "features" : {
    "sex" : "male34553534",
    "location" : "bundang3554534",
    "job" : "programmer"
  }
}

###
